// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwNwU6BPf3TBY1wUT7bF6x5vvEC5r42Z4',
    appId: '1:1049849183581:web:dcbe41d59eb650498e7cb4',
    messagingSenderId: '1049849183581',
    projectId: 'fitapp-380b3',
    authDomain: 'fitapp-380b3.firebaseapp.com',
    storageBucket: 'fitapp-380b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-g9_pshaYLScwFrDbK3oZ-LG1tMHsXn0',
    appId: '1:1049849183581:android:06a99003ef4b45908e7cb4',
    messagingSenderId: '1049849183581',
    projectId: 'fitapp-380b3',
    storageBucket: 'fitapp-380b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCacZdfJmGKRysluVPL2xZGTJdd4fd3A2Q',
    appId: '1:1049849183581:ios:a4f29e21da4e0dfe8e7cb4',
    messagingSenderId: '1049849183581',
    projectId: 'fitapp-380b3',
    storageBucket: 'fitapp-380b3.appspot.com',
    iosBundleId: 'com.example.fitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCacZdfJmGKRysluVPL2xZGTJdd4fd3A2Q',
    appId: '1:1049849183581:ios:a4f29e21da4e0dfe8e7cb4',
    messagingSenderId: '1049849183581',
    projectId: 'fitapp-380b3',
    storageBucket: 'fitapp-380b3.appspot.com',
    iosBundleId: 'com.example.fitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwNwU6BPf3TBY1wUT7bF6x5vvEC5r42Z4',
    appId: '1:1049849183581:web:68a742731f1fae7a8e7cb4',
    messagingSenderId: '1049849183581',
    projectId: 'fitapp-380b3',
    authDomain: 'fitapp-380b3.firebaseapp.com',
    storageBucket: 'fitapp-380b3.appspot.com',
  );

}